name: Fetch Appstore Info

on:
  workflow_dispatch:
  schedule:
    - cron: "0/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node는 기존 14.x 그대로 두었습니다. (필요하면 18/20 LTS로 올리세요)
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true  # Gemfile.lock 기준으로 캐시/설치 자동화

      - run: gem install bundler:2.1.4
      - run: bundle install
      - run: npm install
      - run: gem install fastlane -v '2.219.0'

      - run: npm install

      - run: node Sources/check_status.js
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          KEY_ID: ${{ secrets.KEY_ID }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          LANGUAGE: "ko"
